fix to echo error status

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -17,4 +17,7 @@ jobs:
 
       - name: Run PHP linter
         run: |
-          sh ./php-lint.sh
+          if ! sh ./php-lint.sh; then
+            echo "Lint check failed!"
+            exit 1
+          fi
